spring.application.name=restaurante-service
server.port=9083
eureka.client.serviceUrl.defaultZone=http://localhost:9080/eureka/
spring.data.mongodb.uri=mongodb+srv://root:root@cluster0.uygodqg.mongodb.net/restaurante_db?appName=Cluster0

